name: portainer

networks:
    default:
        name: hss

volumes:
    data:

services:
    portainer:
        image: portainer/portainer-ce:latest
        ports:
            - "9443:9443" # Web Interface
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - data:/data

    portainer_agent:
        # We run a portainer agent due to the fact, that portainer alone cannot browse volumes. This is a workaround.
        image: portainer/agent:latest
        # ports:
        #     - 9001:9001 # Communication Port
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/volumes:/var/lib/docker/volumes