name: denetwork
services:
    proxyman:
        # Default login details:
        # Email:    admin@example.com
        # Password: changeme
        image: jc21/nginx-proxy-manager:latest
        ports:
            - "80:80" # Public HTTP Port
            - "443:443" # Public HTTPS Port
            - "8080:81" # Admin Web Port
        restart: unless-stopped
        volumes:
            - proxyman_data:/data
            - proxyman_letsencrypt:/etc/letsencrypt
        healthcheck:
            test: ["CMD", "/usr/bin/check-health"]
            interval: 60s
            timeout: 10s
            retries: 3
            start_period: 30s

    homarr:
        image: ghcr.io/homarr-labs/homarr:latest
        # ports:
            # - '7575:7575' # Web Interface
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
            - homarr_data:/appdata
        restart: unless-stopped

    watchtower:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        env_file: ./watchtower/.env
        restart: unless-stopped

    cronman:
        image: alseambusher/crontab-ui
        # ports:
        # - 8000:8000 # Web Interface

    wireguard:
        image: ghcr.io/wg-easy/wg-easy
        volumes:
            - etc_wireguard:/etc/wireguard
        ports:
            - "51820:51820/udp"
            # - "51821:51821/tcp"
            # - "80:80" # Web interface
        env_file: ./wireguard/.env
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
            # - NET_RAW # ⚠️ Uncomment if using Podman
        sysctls:
            - net.ipv4.ip_forward=1
            - net.ipv4.conf.all.src_valid_mark=1

networks:
    default:
        name: denetwork
        external: true

volumes:
    proxyman_data:
    proxyman_letsencrypt:

    homarr_data:

    etc_wireguard:
