name: portainer
services:
    portainer:
        container_name: portainer
        image: portainer/portainer-ce:latest
        networks:
            - denetwork
        # ports:
        #     - "9443:9443" # Web Interface
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - data:/data

    portainer_agent:
        container_name: portainer_agent
        image: portainer/agent:2.19.5
        networks:
            - denetwork
        # ports:
        #     - 9001:9001 # Communication Port
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/volumes:/var/lib/docker/volumes

networks:
    denetwork:
        external: true

volumes:
    data:
